import 'package:flutter/material.dart';

abstract class GkSpacers {
  double heightAdjuster(double height);

  double widthAdjuster(double width);

  Widget get height2 => SizedBox(height: heightAdjuster(2));
  Widget get height3 => SizedBox(height: heightAdjuster(3));
  Widget get height4 => SizedBox(height: heightAdjuster(4));
  Widget get height5 => SizedBox(height: heightAdjuster(5));
  Widget get height6 => SizedBox(height: heightAdjuster(6));
  Widget get height7 => SizedBox(height: heightAdjuster(7));
  Widget get height8 => SizedBox(height: heightAdjuster(8));
  Widget get height9 => SizedBox(height: heightAdjuster(9));
  Widget get height10 => SizedBox(height: heightAdjuster(10));
  Widget get height12 => SizedBox(height: heightAdjuster(12));
  Widget get height13 => SizedBox(height: heightAdjuster(13));
  Widget get height14 => SizedBox(height: heightAdjuster(14));
  Widget get height15 => SizedBox(height: heightAdjuster(15));
  Widget get height16 => SizedBox(height: heightAdjuster(16));
  Widget get height17 => SizedBox(height: heightAdjuster(17));
  Widget get height18 => SizedBox(height: heightAdjuster(18));
  Widget get height19 => SizedBox(height: heightAdjuster(19));
  Widget get height20 => SizedBox(height: heightAdjuster(20));
  Widget get height21 => SizedBox(height: heightAdjuster(21));
  Widget get height22 => SizedBox(height: heightAdjuster(22));
  Widget get height24 => SizedBox(height: heightAdjuster(24));
  Widget get height25 => SizedBox(height: heightAdjuster(25));
  Widget get height26 => SizedBox(height: heightAdjuster(26));
  Widget get height28 => SizedBox(height: heightAdjuster(28));
  Widget get height29 => SizedBox(height: heightAdjuster(29));
  Widget get height30 => SizedBox(height: heightAdjuster(30));
  Widget get height32 => SizedBox(height: heightAdjuster(32));
  Widget get height34 => SizedBox(height: heightAdjuster(34));
  Widget get height35 => SizedBox(height: heightAdjuster(35));
  Widget get height36 => SizedBox(height: heightAdjuster(36));
  Widget get height40 => SizedBox(height: heightAdjuster(40));
  Widget get height38 => SizedBox(height: heightAdjuster(38));
  Widget get height44 => SizedBox(height: heightAdjuster(44));
  Widget get height48 => SizedBox(height: heightAdjuster(48));
  Widget get height50 => SizedBox(height: heightAdjuster(50));
  Widget get height52 => SizedBox(height: heightAdjuster(52));
  Widget get height56 => SizedBox(height: heightAdjuster(56));
  Widget get height60 => SizedBox(height: heightAdjuster(60));
  Widget get height62 => SizedBox(height: heightAdjuster(62));
  Widget get height64 => SizedBox(height: heightAdjuster(64));
  Widget get height68 => SizedBox(height: heightAdjuster(68));
  Widget get height70 => SizedBox(height: heightAdjuster(70));
  Widget get height74 => SizedBox(height: heightAdjuster(74));
  Widget get height80 => SizedBox(height: heightAdjuster(80));
  Widget get height88 => SizedBox(height: heightAdjuster(88));
  Widget get height96 => SizedBox(height: heightAdjuster(96));
  Widget get height61 => SizedBox(height: heightAdjuster(61));
  Widget get height100 => SizedBox(height: heightAdjuster(100));
  Widget get height111 => SizedBox(height: heightAdjuster(111));
  Widget get height119 => SizedBox(height: heightAdjuster(119));
  Widget get height130 => SizedBox(height: heightAdjuster(130));
  Widget get height150 => SizedBox(height: heightAdjuster(150));
  Widget get height117 => SizedBox(height: heightAdjuster(117));

  Widget get width4 => SizedBox(width: widthAdjuster(4));
  Widget get width5 => SizedBox(width: widthAdjuster(5));
  Widget get width8 => SizedBox(width: widthAdjuster(8));
  Widget get width6 => SizedBox(width: widthAdjuster(6));
  Widget get width10 => SizedBox(width: widthAdjuster(10));
  Widget get width11 => SizedBox(width: widthAdjuster(11));
  Widget get width12 => SizedBox(width: widthAdjuster(12));
  Widget get width16 => SizedBox(width: widthAdjuster(16));
  Widget get width18 => SizedBox(width: widthAdjuster(18));
  Widget get width20 => SizedBox(width: widthAdjuster(20));
  Widget get width24 => SizedBox(width: widthAdjuster(24));
  Widget get width32 => SizedBox(width: widthAdjuster(32));
  Widget get width76 => SizedBox(width: widthAdjuster(76));
}
